app/web/urls.py
from django.urls import path

from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index,name='index'),
    path('entorno1',views.entorno1,name='entorno1'),
    path('entorno2',views.entorno2,name='entorno2'),
    path('entorno3',views.entorno3,name='entorno3'),
    path('entorno4',views.entorno4,name='entorno4'),
    path('productosPorCategoria/<int:categoria_id>',views.productosPorCategoria,name='productosPorCategoria'),
    path('productosPorNombre',views.productosPorNombre,name='productosPorNombre'),
    path('producto/<int:producto_id>',views.productoDetalle,name='producto'),
    path('carrito',views.carrito,name='carrito'),
    path('agregarCarrito/<int:producto_id>',views.agregarCarrito,name='agregarCarrito'),
    path('limpiarCarrito',views.limpiarCarrito,name='limpiarCarrito'),
    path('registrarPedido',views.registrarPedido,name='registrarPedido'),
    path('eliminarProductoCarrito/<int:producto_id>',views.eliminarProductoCarrito,name='eliminarProductoCarrito'),
    path('crearUsuario',views.crearUsuario,name='crearUsuario'),
    path('loginUsuario',views.loginUsuario,name='loginUsuario'),
    path('cuenta',views.cuentaUsuario,name='cuentaUsuario'),
    path('actualizarCliente',views.actualizarCliente,name='actualizarCliente'),
    path('login',views.loginUsuario,name='loginUsuario'),
    path('logout',views.logoutUsuario,name='logoutUsuario'),
    path('registrarPedido',views.registrarPedido,name='registrarPedido'),
    path('compra',views.compra,name='compra'),
    path('pruebaPaypal',views.view_that_asks_for_money,name='pruebaPaypal'),
    path('confirmarPedido',views.confirmarPedido,name='confirmarPedido'),
    path('gracias',views.gracias,name='gracias'),
    #path('pago/<int:cliente_id>/', views.pago_paypal, name='pago_paypal'),
    #path('paypal/success/<int:cliente_id>/', views.paypal_success, name='paypal_success'),
    #path('paypal/cancel/<int:cliente_id>/', views.paypal_cancel, name='paypal_cancel'),
    path('dw/<int:cliente_id>/', views.dw, name='dw'),
    path('checkout/', views.checkout, name='checkout'),
    path('descargar-pdf/', views.descargar_pdf, name='descargar_pdf'),
    path('pago/paypal/<int:cliente_id>/', views.pago_paypal, name='pago_paypal'),
    path('pago/success/<int:cliente_id>/', views.paypal_success, name='paypal_success'),
    path('pago/cancel/<int:cliente_id>/', views.paypal_cancel, name='paypal_cancel'),
]

app/web/models.py
from django.db import models

# Create your models here.

class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    fecha_registro = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre

class Giro(models.Model):
    nombre = models.CharField(max_length=200)
    fecha_registro = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre


class Proveedor(models.Model):
    nombre = models.CharField(max_length=100)
    direccion = models.TextField(null=True)
    contacto = models.CharField(max_length=100)
    telefono1 = models.CharField(max_length=13)
    telefono2 = models.CharField(max_length=13)
    email = models.EmailField(null=True)
    plazo_credito = models.SmallIntegerField(default=0)
    comentarios = models.TextField(null=True)
    
    def __str__(self):
        return self.nombre

class Producto(models.Model):
    categoria = models.ForeignKey(Categoria,on_delete=models.RESTRICT)
    nombre = models.CharField(max_length=200)
    descripcion = models.TextField(null=True)
    precio = models.DecimalField(max_digits=9,decimal_places=2)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    imagen = models.ImageField(upload_to='productos',blank=True)
    proveedor = models.ForeignKey(Proveedor,on_delete=models.RESTRICT)
    sku = models.CharField(max_length=12, default='')

    def __str__(self):
        return self.nombre

from django.contrib.auth.models import User

class Cliente(models.Model):
    nombre = models.CharField(max_length=60, null=True)
    fecha_compra = models.DateTimeField(auto_now_add=True)
    email = models.EmailField(null=True)
    telefono = models.CharField(max_length=13)
    ciudad = models.CharField(max_length=100, null=True)
    status = models.CharField(max_length=1)
    descargas = models.IntegerField(default=0)  # Nuevo campo para contar las descargas
    
    def __str__(self):
        return self.nombre

class ComunicaCliente(models.Model):
    cliente = models.ForeignKey(Cliente,on_delete=models.RESTRICT)
    fecha_contacto = models.DateTimeField(auto_now_add=True)
    comunicacion = models.TextField(null=True)

    def __str__(self):
        return self.usuario.username

class Pedido(models.Model):
    
    ESTADO_CHOICES = (
        ('0','Solicitado'),
        ('1','Pagado')
    )

    cliente = models.ForeignKey(Cliente,on_delete=models.RESTRICT)   # ForeingKey - relacion de muchos a uno
    fecha_registro = models.DateTimeField(auto_now_add=True)
    numero_pedido = models.CharField(max_length=20,null=True)
    monto_total = models.DecimalField(max_digits=10,decimal_places=2,default=0)
    estado = models.CharField(max_length=1,default='0',choices=ESTADO_CHOICES)   # CON Esto, solo permite 0 o 1

    def __str__(self):
        return self.numero_pedido

class PedidoDetalle(models.Model):
    pedido = models.ForeignKey(Pedido,on_delete=models.RESTRICT)
    producto = models.ForeignKey(Producto,on_delete=models.RESTRICT)
    cantidad = models.IntegerField(default=1)
    subtotal = models.DecimalField(max_digits=10,decimal_places=2)

    def __str__(self):
        return self.producto.nombre

app/web/templates/carrito.html
{% extends 'layout.html' %}
{% block content %}
    <h1 class="maincont-ttl">Carrito</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>Carrito</li>
    </ul>
    <div class="page-styling">
    <div class="woocommerce prod-litems section-list">
        {% for key,value in request.session.cart.items %}
        <article class="prod-li sectls">
            <div class="prod-li-inner">
                <a href="producto.html" class="prod-li-img">
                    <img src="{{ value.imagen }}" alt="">
                </a>
                <div class="prod-li-cont">
                    <div class="prod-li-ttl-wrap">
                        <p>
                            <a href="#">{{value.categoria}}</a>
                        </p>
                        <h3><a href="producto.html">{{ value.nombre }}</a></h3>
                    </div><!--     No Space -->
                <div class="prod-li-prices">
                    <div class="prod-li-price-wrap">
                        <p>Precio</p>
                        <p class="prod-li-price">${{ value.precio }}</p>
                    </div>
                    <div class="prod-li-qnt-wrap">
                        <p class="qnt-wrap prod-li-qnt">
                            <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                            <input type="text" value="{{value.cantidad}}">
                            <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                        </p>
                    </div>
                    <div class="prod-li-total-wrap">
                        <p>Total</p>
                        <p class="prod-li-total">${{value.subtotal}}</p>
                    </div>
                </div><!-- No Space -->         </div>
                <div class="prod-li-info">
                    <div class="prod-li-rating-wrap">
                        <p data-rating="5" class="prod-li-rating">
                            <i class="rating-ico" title="1"></i><i class="rating-ico" title="2"></i><i class="rating-ico" title="3"></i><i class="rating-ico" title="4"></i><i class="rating-ico" title="5"></i>
                        </p>
                        <p class="prod-li-rating-count">12</p>
                    </div>
                    <p class="prod-li-add">
                        <a href="{% url 'web:eliminarProductoCarrito' value.producto_id %}" class="button hover-label prod-addbtn"><i class="icon ion-close-round"></i><span>Eliminar</span></a>
                    </p>
                    <p class="prod-li-information">
                        <a href="#" class="hover-label"><i class="icon ion-more"></i><span>Show Information</span></a>
                    </p>
                </div>
            </div>
            <div class="page-styling prod-li-informations">

                <dl class="prod-li-props">
                    <dt>Marca:</dt>
                    <dd><a href="#">{{value.marca}}</a></dd>
                    <dt>Peso:</dt>
                    <dd>{{value.peso}} kg</dd>
                    <dt>Dimensiones:</dt>
                    <dd>{{value.dimension}}</dd>
                    <dt>Сolor:</dt>
                    <dd>{{value.color}}</dd>
                </dl>
            </div>
        </article>
        {% endfor %}
    </div>


    <div class="cart-actions">
        <div class="coupon">
            <input type="text" placeholder="Coupon code">
            <input type="submit" class="button" value="Apply">
        </div>
        <div class="cart-collaterals">
            <a href="{% url 'web:limpiarCarrito' %}" class="checkout-button button">Limpiar Carrito</a> <!-- 7 -->
            <a href="{% url 'web:registrarPedido' %}" class="checkout-button button">Realizar Pedido</a> <!-- 8 -->
            <div class="order-total">
                <p class="cart-totals-ttl">Total</p>
                <p class="cart-totals-val">${{request.session.cartMontoTotal}}</p>
            </div>
        </div>
    </div>


</div>

{% endblock %}

app/web/templates/compra.html
{% extends 'layout.html' %}
{% block content %}
<h1 class="maincont-ttl">PEDIDO NUM : {{pedido.numero_pedido}}</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>Pedido</li>
    </ul>
<div class="page-styling">
    <div class="woocommerce prod-litems section-list">
            <h2>Fecha : {{pedido.fecha_registro}}</h2>
            {%for detalle in pedido.pedidodetalle_set.all %}
            <article class="prod-li sectls">
                <div class="prod-li-inner">
                    <a href="#" class="prod-li-img">
                        <img src="{{detalle.producto.imagen.url}}" alt="">
                    </a>
                    <div class="prod-li-cont">
                        <div class="prod-li-ttl-wrap">
                            <p>
                                <a href="#">{{detalle.producto.categoria}}</a>
                            </p>
                            <h3><a href="producto.html">{{detalle.producto.nombre}}</a></h3>
                        </div>
                        <div class="prod-li-prices">
                            <div class="prod-li-price-wrap">
                                <p>Precio</p>
                                <p class="prod-li-price">${{detalle.producto.precio}}</p>
                            </div>
                        </div>
                        <div class="prod-li-qnt-wrap">
                            <p class="qnt-wrap prod-li-qnt">
                                <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                <input type="text" value="{{detalle.cantidad}}">
                                <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                            </p>
                        </div>
                        <div class="prod-li-total-wrap">
                            <p>Total</p>
                            <p class="prod-li-total">${{detalle.subtotal}}</p>
                        </div>
                    </div>
                </div>
            </article>
            {% endfor %}
    </div>
    <div class="cart-actions">
            <div class="cart-collaterals">
                {{formPaypal.render}}
                <div class="order-total">
                    <p class="cart-totals-ttl">Total</p>
                    <p class="cart-totals-val">${{pedido.monto_total}}</p>
                </div>
            </div>
    </div>
</div>
{% endblock %}

app/web/templates/cuenta.html
{% extends 'layout.html' %}
{% block content %}
<h1 class="maincont-ttl">Bienvenido - {{ user.username }}</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>Mi Cuenta</li>
    </ul>
    <h2>{{mensaje}}</h2>
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <h2>Datos Personales</h2>
                    <form method="post" action="{% url 'web:actualizarCliente' %}" class="register">
                        {% csrf_token %}
                        {{ frmCliente}}  
                        <p class="auth-submit">
                            <input type="submit" value="Actualizar Datos">
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </article>
{% endblock %}

app/web/templates/entorno1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hijos Felices</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ephesis&family=IBM+Plex+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Noto+Sans:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}?v=124">
</head>
<body>
    <div class="site-header">
        <h1>Construyendo un mundo mejor... para tus hijos</h1>
    </div>

    <div class="space"></div>
    
    <div class="container">
        <h2>La Comunicación con tu Hijo es Clave</h2>
        <div class="space"></div>
    
        <div class="imagen">
            <h3>¿Te preocupa la rebeldía de tu hijo?</h3>
            <!-- <p>Has empezado a notar que tu hijo contesta mal, no quiere hablar, se encierra en su habitación</p> -->
            
        </div>
        <div class="space"></div>
        <div class="imagen">
            <h3>¿Hay discusiones y conflictos frecuentes en la familia?</h3>
            <!-- <p>Son cada vez más frecuentes las discusiones por cosas sin importancia</p> -->
        </div>
        <div class="space"></div>
        <div class="imagen">
            <h3>¿Quieres establecer límites claros, sin necesidad de convencer a tu hijo de seguirlos?</h3>
            <!-- <p>Aprenderás como definir reglas y límites en casa, sin discusiones</p> -->
        </div>
        <div class="space"></div>
        <div class="imagen">
            <h3>¿Te preocupa el comportamiento de tu hijo?</h3>
            <!-- <p>Quieres eliminar esas actitudes negativas?
               Muchas veces no sabemos exactamente que hacer. 
            </p> -->
        </div>
        
        <div class="space"></div>
        <div class="space"></div>
        <a class="boton" href="{% url 'web:entorno2' %}">  <!-- 3 OJO-->    
            <h3>Continuar</h3>
         </a>
    </div>
</body>
</html>

app/web/templates/entorno2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hijos Felices</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ephesis&family=IBM+Plex+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Noto+Sans:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}?v=124">
</head>
<body>
    <div class="site-header">
        <h1>El Entorno: Drogas, Entorno Negativo, Redes Sociales</h1>
    </div>
    <div class="container">
        <div class="space"></div> 
        <div class="imagen">
            <h3>¿Estás notando actitudes negativas en el comportamiento de tu hijo?</h3>
            <!-- <p>Tu hijo se hará consciente de esas actitudes negativas para poder eliminarlas</p> -->
        </div>        
        <div class="space"></div> 
        <div class="imagen">
            <h3>Piensas que sus amistades no son las adecuadas</h3>
            <!-- <p>Podrás mostrar a tu hijo una forma sencilla para analizar y decidir si una amistad le conviene o no</p> -->
        </div>
        <div class="space"></div>
        <div class="imagen">
            <h3>¿Quieres estar 100% seguro de la decisión que va a tomar tu hijo si algún amigo le ofrece drogas?</h3>
            <!-- <p>Con este método vas a estar seguro de la decisión que va a tomar tu hijo</p> -->
        </div>
        <div class="space"></div> 
        <div class="imagen">
            <h3>¿Se encierra en su habitación para estar en el celular y redes sociales?</h3>
            <!-- <p>No te hace caso de limitar el uso del celular</p> -->
        </div>
        <div class="space"></div> 
        <div class="imagen">
            <h3>¿Te gustaría poder aumentar la seguridad y autoestima de tu hijo?</h3>
            <!-- <p>Encontrarás un método para aumentar su seguridad y autoestima a niveles que no te imaginabas</p> -->
        </div>

        <div class="space"></div> 
        <div class="space"></div>
        <a class="boton" href="{% url 'web:entorno3' %}"> 
            <h3>Continuar</h3>
        </a>
     </div>
</body>
</html>

app/web/templates/entorno3.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hijos Felices</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ephesis&family=IBM+Plex+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Noto+Sans:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}?v=124">
</head>
<body>
    <div class="site-header">
        <h1>Conoce el Método, es Increíblemente Eficaz</h1>
    </div>
    <div class="space"></div>
    <div class="container">
        <div class="imagen">
            <h3>¿Quieres que tu hijo se convierta en una persona
                de bien, responsable y con alta autoestima?</h3>
            <!-- <p>Encontrarás un método fácil y comprobado para hacerlo posible</p> -->
        </div>
        <div class="space"></div>
        <div class="imagen">
            <h3>¿Te gustaría ver a tu hijo seguro e independiente 
                (en un futuro no muy lejano)?</h3>
            <!-- <p>Esa es la mayor satisfacción de un padre/madre de familia </p> -->
        </div>
        <div class="space"></div>
        <div class="imagen">
            <h3>¿Puede tu hijo actualmente tomar sus propias 
                decisiones adecuadamente?</h3>
            <!-- <p>Encontrarás un método sencillo para tomar cualquier decisión de la manera correcta</p> -->
        </div>
        <div class="space"></div>
        <div class="imagen">
            <h3>¿Te gustaría aumentar la confianza con tu hijo 
                de tal manera que la conversación fluya entre 
                ambos de manera natural, sin límites?</h3>
            <!-- <p>Siguiendo los pasos del método que te mostramos en este ebook, va a aumentar drásticamente la confianza y la comunicación con tu hijo</p> -->
        </div>

        <div class="space"></div>
        <div class="space"></div>
        <div class="space"></div>
        <div class="imagen2">
            <h5>La formación de los hijos es una gran 
                responsabilidad, quizá la más importante que tenemos
                como padres y madres de familia.
                Queremos ayudar a la mayor cantidad
                de familias llevándoles un método fácil y práctico
                que eliminará: 
            <br> 
                • todas las barreras de comunicación 
            <br>
                • toda influencia negativa que recibe de redes
                  sociales y entorno
            <br>
                Aumentando la confianza y seguridad;
                tu hijo usará esta herramienta en automático, 
                sin pensarlo. 
            </h5>
        </div>    
        <div class="space"></div>
        <div class="space"></div>
        <a class="boton" href="{% url 'web:entorno4' %}"> 
            <h3>Continuar</h3>
        </a>
    </div> <!-- container -->

</body>
</html>

app/web/templates/pedido.html
{% extends 'layout.html' %}
{% block content %}
<h1 class="maincont-ttl">REGISTRO DE PEDIDO</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>pedido</li>
    </ul>
    <form method="post" action="{% url 'web:confirmarPedido' %}" class="register">
    {% csrf_token %}
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <h2>Datos Personales</h2>
                    <p>
                        <label for="username">Nombres<span class="required">*</span></label>
                        {{frmCliente.nombre}}
                    </p>
                    <p>
                        <label for="username">Apellidos<span class="required">*</span></label>
                        {{frmCliente.apellidos}}
                    </p>
                    <p>
                        <label for="username">Email<span class="required">*</span></label>
                        {{frmCliente.email}}
                    </p>
                </div>
                <div class="auth-col">
                    <h2>Datos Envio</h2>
                    <p>
                        <label for="username">Telefono<span class="required">*</span></label>
                        {{frmCliente.telefono}}
                    </p>
                    <p>
                        <label for="username">Dirección<span class="required">*</span></label>
                        {{frmCliente.direccion}}
                    </p>
                </div>
            </div>
        </div>
    </article>
    <article class="page-cont">
        <div class="page-styling">
            <h2>Confirmación de Productos</h2>
            <div class="woocommerce prod-litems section-list">
                {% for key,value in request.session.cart.items %}
                <article class="prod-li sectls">
                    <div class="prod-li-inner">
                        <a href="#" class="prod-li-img">
                            <img src="{{ value.imagen }}" alt="">
                        </a>
                        <div class="prod-li-cont">
                            <div class="prod-li-ttl-wrap">
                                <p>
                                    <a href="#">value.categoria</a>
                                </p>
                                <h3><a href="product.html">{{ value.nombre }}</a></h3>
                            </div>
                            <div class="prod-li-prices">
                                <div class="prod-li-price-wrap">
                                    <p>Precio</p>
                                    <p class="prod-li-price">${{value.precio}}</p>
                                </div>
                            </div>
                            <div class="prod-li-qnt-wrap">
                                <p class="qnt-wrap prod-li-qnt">
                                    <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                    <input type="text" value="{{value.cantidad}}">
                                    <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                                </p>
                            </div>
                            <div class="prod-li-total-wrap">
                                <p>Total</p>
                                <p class="prod-li-total">${{value.subtotal}}</p>
                            </div>
                        </div>
                    </div>
                </article>
                {% endfor %}
        </div>
        <div class="cart-actions">
                <div class="cart-collaterals">
                    <div class="order-total">
                        <p class="cart-totals-ttl">Total</p>
                        <p class="cart-totals-val">${{request.session.cartMontoTotal}}</p>
                    </div>
                </div>
        </div>
        </div>
    </article>
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <p class="auth-submit">
                        <input type="submit" value="Confirmar Pedido">
                    </p>
            </div>
        </div>
    </article>
    </form>
{% endblock %}

app/web/templates/plantilla.html
{% extends 'layout.html' %}
{% block content %}
{% endblock %}

app/web/templates/success.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Hijos Felices</title>
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <style>
        body {
            background-color: #e8f5e9;
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .mensaje {
            background: white;
            padding: 2rem 3rem;
            border-radius: 1rem;
            text-align: center;
            box-shadow: 0 0 15px rgba(0,0,0,0.1);
        }
        .mensaje h1 {
            color: #2e7d32;
        }
        .mensaje p {
            font-size: 1.1rem;
        }
        .btn-descargar {
            display: inline-block;
            padding: 10px 20px;
            font-size: 18px;
            color: white;
            background-color: #007bff;
            text-decoration: none;
            border-radius: 5px;
        }
        .btn-descargar:hover {
            background-color: #0056b3;
        }

    </style>
</head>
<body>
    <div class="mensaje">
        <h1>¡Gracias por tu pago!</h1>
        <p>Tu transacción fue exitosa, {{ cliente.nombre }}.</p>
        <p>Puedes descargar el eBook aqui:</p>
        <br>
        <a href="{% url 'web:descargar_pdf' %}" target="_blank" class="btn-descargar">Descargar en formato PDF</a>
        <!-- <p>Revisa tu correo electrónico: <strong>{{ cliente.email }}</strong> para más detalles.</p>  -->
        <br>
        <br>
        <a class="btn" href="{% url 'web:index' %}">Volver al Inicio</a>
    </div>
</body>
</html>